name: chatting_app
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  google_fonts: ^5.1.0
  cupertino_icons: ^1.0.2
  # this is for the messaages icon
  font_awesome_flutter: ^10.5.0
  # listens for the keyboard changes
  flutter_keyboard_visibility: ^5.4.1
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  cloud_firestore: ^4.9.1
  provider: ^6.0.5
  url_launcher: ^6.1.14
  permission_handler: ^11.0.0
  clipboard: ^0.1.3
  audioplayers: ^5.1.0
  firebase_messaging: ^14.6.8
  http: ^1.1.0
  image_picker: ^1.0.4
  firebase_storage: ^11.2.8
  cached_network_image: ^3.3.0
  firebase_app_check: ^0.2.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0


flutter:

 
  uses-material-design: true


  assets:
    - assets/message_sent_sound_effect.mp3